### ISSUE TITLE
No ObjectCodec defined for the generator, can only serialize simple wrapper types

### ISSUE THREAD

**Issue by particlememory** [bjornharrtell/jdbc-http-server#7]
Hi.

For table that on Mysql with date time column

On the GETS Rows API
/db/dbname/schemas/schemaname/tables/tablenames/rows

Response return: 
No ObjectCodec defined for the generator, can only serialize simple wrapper types (type passed java.sql.Timestamp)

**Comment by bjornharrtell** [comment]
Sorry, not trivial to fix.
